[package]
name = "eranthis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
miette = { version = "7.6.0", features = ["fancy"] }
phf = "0.13.1"
phf_macros = "0.13.1"
pomelo = "0.2.3"
thiserror = "2.0.17"
